#!/usr/bin/env python3
"""One-off generator: merge landing + pango/wheel + citizen settings + lawyer settings into ARB files."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "lib" / "l10n"

landing = {
    "he": {
        "brandEyebrow": "הגנה משפטית מיידית",
        "navHome": "בית",
        "navFeatures": "תכונות",
        "navPricing": "תמחור",
        "navHow": "איך זה עובד",
        "navContact": "צור קשר",
        "navCareers": "קריירה",
        "navLogin": "כניסה",
        "navRegister": "הרשמה",
        "heroEyebrow": "VETO · זמין 24/7 בכל הארץ",
        "heroTitleL1": "ההגנה המשפטית",
        "heroTitleL2": "שלך — תמיד ",
        "heroTitleEm": "בהישג יד",
        "heroBody": "VETO מחבר אותך לעורך דין מתמחה תוך שניות בכל מצב חירום, עם תיעוד שיחה מלא וכספת מוצפנת.",
        "heroCta": "לחץ SOS",
        "heroSecondary": "גלה עוד",
        "miniStatBefore": "חיבור ב-",
        "miniStatEm": "3 שניות",
        "miniStatSuffix": "עו״ד פלילי זמין",
        "proof1Num": "4.9",
        "proof1Lbl": "דירוג ממשתמשים",
        "proof2Num": "3″",
        "proof2Lbl": "זמן חיבור ממוצע",
        "proof3Num": "+200",
        "proof3Lbl": "עורכי דין רשומים",
        "feat1Title": "הגנה מיידית",
        "feat1Body": "חיבור לעורך דין מתמחה תוך שניות, בכל מצב חירום משפטי — חקירה, עצירה, סכסוך.",
        "feat2Title": "קשר ישיר עם עו\"ד",
        "feat2Body": "קולי, וידאו או טקסט — הבחירה שלך. תיעוד שיחה מלא, נשמר אך ורק בכספת המוצפנת שלך.",
        "feat3Title": "פרטיות מלאה",
        "feat3Body": "הצפנה End-to-End, גיבוי בכספת אישית, וגישה רק לידיך — לא לחברה ולא לרשויות.",
        "stat1num": "24/7",
        "stat1lbl": "הגנה משפטית",
        "stat2num": "Real",
        "stat2lbl": "עורכי דין אמיתיים",
        "stat3num": "+3",
        "stat3lbl": "שפות נתמכות",
        "stat4num": "Live",
        "stat4lbl": "שיגור בזמן אמת",
        "stackTitle": "רצף תגובה אחד",
        "stackKicker": "איך זה עובד",
        "stack1Title": "זיהוי מצב",
        "stack1Body": "נחקרים, עצורים, או מעורבים בתאונה? המערכת מתאימה מענה מיידי.",
        "stack2Title": "שיחה עם AI",
        "stack2Body": "הסוכן מסדר את הידע, מחדד שאלות, ומכוון לצעד המשפטי הבא.",
        "stack3Title": "חיבור אנושי",
        "stack3Body": "אם נדרש עו\"ד — המשרד מזניק איש מקצוע זמין עם עדיפות לשפה הרלוונטית.",
        "pricingTitle": "מנוי חודשי",
        "pricingHeroTitle": "שכבת הגנה תמידית",
        "pricingIntro": "הכל במסלול אחד — עוזר AI, ספריית זכויות, כספת מוצפנת ושיגור עורך דין בזמן אמת.",
        "pricingPrice": "₪19.90",
        "pricingPeriod": "לחודש",
        "pricingLine1": "עוזר AI משפטי ללא הגבלה",
        "pricingLine2": "תרחישים, זכויות ותיעוד ראיות",
        "pricingLine3": "שיגור עורך דין באירוע חי לפי שימוש",
        "pricingLine4": "כספת מוצפנת לשמירת מסמכים",
        "pricingLine5": "תמיכה בעברית · English · Русский",
        "ctaTitle": "בונים שכבת הגנה לפני שהאירוע מתחיל",
        "ctaBody": "ההרשמה קצרה. מהרגע שהיא מסתיימת, כל חירום משפטי מקבל מסך ברור ומוכן לפעולה.",
        "ctaBtn": "לעבור לאשף",
        "ctaSecondary": "דבר עם איש מכירות",
        "footer": "VETO LEGAL · מערכת תגובה משפטית חכמה, מהירה ורב-לשונית",
        "linkPrivacy": "מדיניות פרטיות",
        "linkTerms": "תנאי שימוש",
        "linkContact": "צור קשר",
        "linkCareers": "קריירה",
    },
    "en": {
        "brandEyebrow": "Instant legal defense",
        "navHome": "Home",
        "navFeatures": "Features",
        "navPricing": "Pricing",
        "navHow": "How it works",
        "navContact": "Contact",
        "navCareers": "Careers",
        "navLogin": "Sign in",
        "navRegister": "Sign up",
        "heroEyebrow": "VETO · 24/7 nationwide",
        "heroTitleL1": "Your legal protection",
        "heroTitleL2": " — always ",
        "heroTitleEm": "within reach",
        "heroBody": "VETO connects you with a specialized lawyer within seconds in any emergency — full conversation logging and an encrypted vault.",
        "heroCta": "SOS",
        "heroSecondary": "Learn more",
        "miniStatBefore": "Connect in ",
        "miniStatEm": "3 seconds",
        "miniStatSuffix": "criminal lawyer on duty",
        "proof1Num": "4.9",
        "proof1Lbl": "User rating",
        "proof2Num": "3″",
        "proof2Lbl": "Avg. connect time",
        "proof3Num": "+200",
        "proof3Lbl": "Registered lawyers",
        "feat1Title": "Immediate protection",
        "feat1Body": "Connect with a specialized lawyer within seconds — investigations, detention, disputes.",
        "feat2Title": "Direct lawyer access",
        "feat2Body": "Voice, video, or text — your choice. Full call logs stored only in your encrypted vault.",
        "feat3Title": "Full privacy",
        "feat3Body": "End-to-end encryption, backup in your vault, access only for you — not the company or authorities.",
        "stat1num": "24/7",
        "stat1lbl": "Legal Protection",
        "stat2num": "Real",
        "stat2lbl": "Lawyers",
        "stat3num": "+3",
        "stat3lbl": "Languages",
        "stat4num": "Live",
        "stat4lbl": "Dispatch",
        "stackTitle": "One response chain",
        "stackKicker": "How it works",
        "stack1Title": "Situation awareness",
        "stack1Body": "Questioned, detained, or in an accident? The system responds immediately.",
        "stack2Title": "AI conversation",
        "stack2Body": "The agent organizes facts, sharpens questions, and guides your next legal step.",
        "stack3Title": "Human handoff",
        "stack3Body": "When a lawyer is required — dispatch with priority for the right language.",
        "pricingTitle": "Monthly Plan",
        "pricingHeroTitle": "Always-on protection layer",
        "pricingIntro": "Everything on one plan — AI assistant, rights library, encrypted vault and live lawyer dispatch.",
        "pricingPrice": "₪19.90",
        "pricingPeriod": "per month",
        "pricingLine1": "Unlimited legal AI assistant",
        "pricingLine2": "Rights scenarios and evidence tools",
        "pricingLine3": "Live lawyer dispatch billed by event",
        "pricingLine4": "Encrypted vault for your documents",
        "pricingLine5": "Hebrew · English · Русский support",
        "ctaTitle": "Build your legal safety layer before the incident begins",
        "ctaBody": "Registration is short. Once done, every legal emergency starts from one clear interface.",
        "ctaBtn": "Open the wizard",
        "ctaSecondary": "Talk to sales",
        "footer": "VETO LEGAL · Fast, intelligent, multilingual legal response",
        "linkPrivacy": "Privacy",
        "linkTerms": "Terms",
        "linkContact": "Contact",
        "linkCareers": "Careers",
    },
    "ru": {
        "brandEyebrow": "Мгновенная защита",
        "navHome": "Главная",
        "navFeatures": "Функции",
        "navPricing": "Тарифы",
        "navHow": "Как это работает",
        "navContact": "Контакты",
        "navCareers": "Карьера",
        "navLogin": "Вход",
        "navRegister": "Регистрация",
        "heroEyebrow": "VETO · 24/7 по всей стране",
        "heroTitleL1": "Ваша юридическая защита",
        "heroTitleL2": " — всегда ",
        "heroTitleEm": "рядом",
        "heroBody": "VETO соединяет вас со специализированным адвокатом за секунды в любой экстренной ситуации — полное журналирование и зашифрованное хранилище.",
        "heroCta": "SOS",
        "heroSecondary": "Узнать больше",
        "miniStatBefore": "Подключение за ",
        "miniStatEm": "3 секунды",
        "miniStatSuffix": "адвокат на линии",
        "proof1Num": "4.9",
        "proof1Lbl": "Оценка пользователей",
        "proof2Num": "3″",
        "proof2Lbl": "Среднее время связи",
        "proof3Num": "+200",
        "proof3Lbl": "Зарегистрированных адвокатов",
        "feat1Title": "Мгновенная защита",
        "feat1Body": "Связь со специализированным адвокатом за секунды — допрос, задержание, конфликт.",
        "feat2Title": "Прямой контакт с адвокатом",
        "feat2Body": "Голос, видео или текст — как удобно. Полные логи только в вашем зашифрованном хранилище.",
        "feat3Title": "Полная конфиденциальность",
        "feat3Body": "Сквозное шифрование, резерв в хранилище, доступ только у вас — не у компании и не у органов.",
        "stat1num": "24/7",
        "stat1lbl": "Защита",
        "stat2num": "Живые",
        "stat2lbl": "Адвокаты",
        "stat3num": "+3",
        "stat3lbl": "Языка",
        "stat4num": "Живой",
        "stat4lbl": "Вызов",
        "stackTitle": "Одна цепочка реакции",
        "stackKicker": "Как это работает",
        "stack1Title": "Определение ситуации",
        "stack1Body": "Допрос, задержание или ДТП? Система сразу подбирает ответ.",
        "stack2Title": "Диалог с AI",
        "stack2Body": "Агент структурирует факты, уточняет вопросы и ведёт к следующему шагу.",
        "stack3Title": "Связь с человеком",
        "stack3Body": "Если нужен адвокат — оперативный вызов с приоритетом языка.",
        "pricingTitle": "Ежемесячный план",
        "pricingHeroTitle": "Постоянная защита",
        "pricingIntro": "Всё в одном тарифе — AI-ассистент, библиотека прав, хранилище и вызов адвоката.",
        "pricingPrice": "₪19.90",
        "pricingPeriod": "в месяц",
        "pricingLine1": "Безлимитный юридический AI",
        "pricingLine2": "Сценарии прав и сбор доказательств",
        "pricingLine3": "Вызов адвоката по событию",
        "pricingLine4": "Зашифрованное хранилище документов",
        "pricingLine5": "Иврит · English · Русский",
        "ctaTitle": "Создайте защитный слой до начала инцидента",
        "ctaBody": "Регистрация занимает минуту. После этого любая экстренная ситуация начинается с одного экрана.",
        "ctaBtn": "Перейти к мастеру",
        "ctaSecondary": "Связаться с отделом продаж",
        "footer": "VETO LEGAL · Быстрая, умная и мультиязычная юридическая реакция",
        "linkPrivacy": "Конфиденциальность",
        "linkTerms": "Условия",
        "linkContact": "Контакты",
        "linkCareers": "Карьера",
    },
}

pango_extra = {
    "en": {
        "navPersonalArea": "Personal area",
        "navMenu": "Menu",
        "menuSearchPlaceholder": "What would you like to search?",
        "menuSmartServices": "Smart legal services",
        "menuBenefits": "Benefits with VETO",
        "menuPlans": "Plans & pricing",
        "menuCare": "VETO Care",
        "menuContact": "Contact & support",
        "menuBusiness": "VETO for business",
        "menuTerms": "Terms of use",
        "menuSafeUse": "Safe use",
        "menuAbout": "About",
        "menuCareers": "Careers",
        "wheelKicker": "ONE RESPONSE CHAIN",
        "wheelTellMore": "Tell me more +",
        "fabAskAi": "Ask VETO AI",
        "fabCustomerSupport": "Customer support",
        "fabAccessibility": "Accessibility",
        "wheel1Label": "Traffic stop",
        "wheel2Label": "Accident",
        "wheel3Label": "Detention",
        "wheel4Label": "Dispute",
        "wheel5Label": "General counsel",
        "wheel1Title": "Rights at a traffic stop",
        "wheel1Body": "A calm checklist: documentation, what you may decline, and when to escalate to a lawyer.",
        "wheel1Point1": "Note badge number and reason for the stop.",
        "wheel1Point2": "Many voluntary searches can be declined — know your context.",
        "wheel1Point3": "Tap SOS to route a criminal lawyer in seconds.",
        "wheel2Title": "After a road accident",
        "wheel2Body": "Evidence, reporting, insurance — structured steps so nothing is missed.",
        "wheel2Point1": "Secure scene photos and witness contacts if safe.",
        "wheel2Point2": "Exchange details and file reports as required.",
        "wheel2Point3": "Keep everything in your encrypted VETO vault.",
        "wheel3Title": "Investigation or detention",
        "wheel3Body": "Silence strategy, lawyer timing, and custody basics — without panic.",
        "wheel3Point1": "You have the right to consult counsel.",
        "wheel3Point2": "Avoid signing without understanding.",
        "wheel3Point3": "Dispatch keeps language preference in mind.",
        "wheel4Title": "Domestic or civil dispute",
        "wheel4Body": "De-escalation, protective steps, and documentation for later proceedings.",
        "wheel4Point1": "Prioritize safety and clear boundaries.",
        "wheel4Point2": "Log threats and incidents with timestamps.",
        "wheel4Point3": "Human handoff when stakes rise.",
        "wheel5Title": "General legal guidance",
        "wheel5Body": "AI structures facts; humans decide — VETO bridges both.",
        "wheel5Point1": "Unlimited scenario prompts in your plan.",
        "wheel5Point2": "Rights library tuned to your jurisdiction context.",
        "wheel5Point3": "Upgrade path to live counsel any time.",
    },
    "he": {
        "navPersonalArea": "איזור אישי",
        "navMenu": "תפריט",
        "menuSearchPlaceholder": "מה תרצה לחפש?",
        "menuSmartServices": "שירותים משפטיים חכמים",
        "menuBenefits": "הטבות ב-VETO",
        "menuPlans": "מסלולים ותמחור",
        "menuCare": "VETO Care",
        "menuContact": "יצירת קשר ותמיכה",
        "menuBusiness": "VETO לעסקים",
        "menuTerms": "תנאי שימוש",
        "menuSafeUse": "שימוש בטוח",
        "menuAbout": "אודות",
        "menuCareers": "קריירה",
        "wheelKicker": "שרשרת תגובה אחת",
        "wheelTellMore": "ספרו לי עוד +",
        "fabAskAi": "שאל את VETO AI",
        "fabCustomerSupport": "שירות לקוחות",
        "fabAccessibility": "נגישות",
        "wheel1Label": "עצירת תנועה",
        "wheel2Label": "תאונה",
        "wheel3Label": "מעצר / חקירה",
        "wheel4Label": "סכסוך",
        "wheel5Label": "ייעוץ כללי",
        "wheel1Title": "זכויות בעצירת תנועה",
        "wheel1Body": "רשימת בדיקה רגועה: תיעוד, מה אפשר לסרב, ומתי לעלות לעו״ד.",
        "wheel1Point1": "רשמו מספר תג וסיבת העצירה.",
        "wheel1Point2": "חיפוש מרצון — לעיתים ניתן לסרב; התאימו להקשר.",
        "wheel1Point3": "לחצו SOS לחיבור עו״ד פלילי תוך שניות.",
        "wheel2Title": "אחרי תאונת דרכים",
        "wheel2Body": "ראיות, דיווחים וביטוח — צעדים מסודרים כדי שלא יוחמץ כלום.",
        "wheel2Point1": "צילומים ועדים אם הבטיחות מאפשרת.",
        "wheel2Point2": "החלפת פרטים ודיווח כנדרש.",
        "wheel2Point3": "שמרו הכל בכספת המוצפנת של VETO.",
        "wheel3Title": "חקירה או מעצר",
        "wheel3Body": "אסטרטגיית שתיקה, תזמון עו״ד ויסודות מעצר — בלי פאניקה.",
        "wheel3Point1": "יש זכות להתייעצות עם עו״ד.",
        "wheel3Point2": "הימנעו מחתימה בלי הבנה.",
        "wheel3Point3": "השיגור שומר על עדיפות שפה.",
        "wheel4Title": "סכסוך ביתי או אזרחי",
        "wheel4Body": "הרגעה, הגנה עצמית ותיעוד להליכים עתידיים.",
        "wheel4Point1": "בטיחות לפני הכל.",
        "wheel4Point2": "תעדו איומים ואירועים עם חותמת זמן.",
        "wheel4Point3": "מעבר לעו״ד כשהסיכונים גדלים.",
        "wheel5Title": "הכוונה משפטית כללית",
        "wheel5Body": "ה-AI מסדר עובדות; האדם מחליט — VETO מחבר ביניהם.",
        "wheel5Point1": "תרחישים ללא הגבלה במנוי.",
        "wheel5Point2": "ספריית זכויות מותאמת להקשר.",
        "wheel5Point3": "שדרוג לייעוץ חי בכל עת.",
    },
    "ru": {
        "navPersonalArea": "Личный кабинет",
        "navMenu": "Меню",
        "menuSearchPlaceholder": "Что вы хотите найти?",
        "menuSmartServices": "Умные юридические сервисы",
        "menuBenefits": "Преимущества VETO",
        "menuPlans": "Тарифы",
        "menuCare": "VETO Care",
        "menuContact": "Контакты и поддержка",
        "menuBusiness": "VETO для бизнеса",
        "menuTerms": "Условия использования",
        "menuSafeUse": "Безопасное использование",
        "menuAbout": "О нас",
        "menuCareers": "Карьера",
        "wheelKicker": "ОДНА ЦЕПОЧКА РЕАКЦИИ",
        "wheelTellMore": "Расскажите подробнее +",
        "fabAskAi": "Спросить VETO AI",
        "fabCustomerSupport": "Поддержка клиентов",
        "fabAccessibility": "Доступность",
        "wheel1Label": "Остановка",
        "wheel2Label": "ДТП",
        "wheel3Label": "Задержание",
        "wheel4Label": "Спор",
        "wheel5Label": "Консультация",
        "wheel1Title": "Права при остановке",
        "wheel1Body": "Спокойный чеклист: документирование, от чего можно отказаться, когда звать адвоката.",
        "wheel1Point1": "Запишите номер жетона и причину остановки.",
        "wheel1Point2": "Добровольный обыск часто можно отклонить — смотрите контекст.",
        "wheel1Point3": "SOS — маршрут к адвокату за секунды.",
        "wheel2Title": "После ДТП",
        "wheel2Body": "Доказательства, заявления, страховка — по шагам.",
        "wheel2Point1": "Фото и свидетели, если безопасно.",
        "wheel2Point2": "Обмен данными и отчёты по правилам.",
        "wheel2Point3": "Храните всё в зашифрованном хранилище VETO.",
        "wheel3Title": "Допрос или задержание",
        "wheel3Body": "Стратегия молчания, время адвоката, основы содержания.",
        "wheel3Point1": "Право на консультацию.",
        "wheel3Point2": "Не подписывайте без понимания.",
        "wheel3Point3": "Диспетчеризация с учётом языка.",
        "wheel4Title": "Бытовой или гражданский спор",
        "wheel4Body": "Деэскалация, защита и документирование.",
        "wheel4Point1": "Безопасность прежде всего.",
        "wheel4Point2": "Фиксируйте угрозы с метками времени.",
        "wheel4Point3": "Передача адвокату при росте риска.",
        "wheel5Title": "Общая юридическая помощь",
        "wheel5Body": "AI структурирует факты; человек решает — VETO соединяет.",
        "wheel5Point1": "Безлимит сценариев в тарифе.",
        "wheel5Point2": "Библиотека прав под контекст.",
        "wheel5Point3": "Переход к живому адвокату в любой момент.",
    },
}

# Citizen settings (prefix cset_) — English from settings_screen
cset_en = {
    "csetTitle": "Settings",
    "csetProfile": "Profile",
    "csetName": "Name",
    "csetPhone": "Phone",
    "csetEmail": "Email",
    "csetLanguage": "Language",
    "csetHebrew": "עברית",
    "csetEnglish": "English",
    "csetRussian": "Русский",
    "csetNotifications": "Notifications",
    "csetNotifyEmergency": "Emergency alerts",
    "csetNotifyUpdates": "System updates",
    "csetNotifySms": "SMS",
    "csetSubscription": "Subscription",
    "csetCurrentPlan": "Current plan",
    "csetUpgrade": "Upgrade",
    "csetManagePayment": "Manage payment",
    "csetLawyerSettings": "Lawyer settings",
    "csetAvailability": "Availability",
    "csetSpecializations": "Specializations",
    "csetContactLinks": "Contact links",
    "csetWhatsapp": "WhatsApp",
    "csetTelegram": "Telegram",
    "csetAdminSettings": "Admin settings",
    "csetSystemEmail": "System email",
    "csetMaintenanceMode": "Maintenance mode",
    "csetMaxFileSizeMb": "Max file size (MB)",
    "csetDefaultQuotaMb": "Default file quota (MB)",
    "csetDanger": "Danger Zone",
    "csetDeleteAccount": "Delete account",
    "csetDeleteConfirm": "This is irreversible. Confirm?",
    "csetSave": "Save changes",
    "csetSaved": "Settings saved",
    "csetCancel": "Cancel",
    "csetYes": "Yes",
    "csetNo": "No",
    "csetLogout": "Sign out",
    "csetLegalSection": "Legal",
    "csetPrivacyPolicy": "Privacy policy",
    "csetTermsOfService": "Terms of service",
    "csetDeployBuild": "Deploy build",
    "csetAddLink": "Add link",
    "csetPlanFree": "Free",
    "csetPlanBasic": "Basic",
    "csetPlanPro": "Pro",
    "csetAgoraCallTitle": "Video/audio calls (Agora)",
    "csetAgoraCallBody": "VETO routes video and audio calls through Agora RTC. No manual STUN/TURN settings are required. Allow camera and microphone in your browser or device settings.",
    "csetWebrtcTitle": "WebRTC calls",
    "csetWebrtcHint": "Applies to the next call. STUN from here; if the backend exposes TURN/ICE env vars, they are merged automatically.",
    "csetWebrtcIce": "STUN server set",
    "csetWebrtcIceMin": "Minimal (3 servers)",
    "csetWebrtcIceExt": "Extended (5 servers)",
    "csetWebrtcPool": "ICE candidate pool size",
    "csetWebrtcEcho": "Echo cancellation",
    "csetWebrtcNoise": "Noise suppression",
    "csetWebrtcAgc": "Auto gain control",
    "csetWebrtcRes": "Video resolution",
    "csetWebrtcResSd": "SD 640×480",
    "csetWebrtcResHd": "HD 1280×720",
    "csetWebrtcResFhd": "Full HD 1920×1080",
    "csetWebrtcFacing": "Camera facing",
    "csetWebrtcFacingUser": "Front (user)",
    "csetWebrtcFacingEnv": "Back (environment)",
    "csetWebrtcBundle": "Bundle policy",
    "csetWebrtcBundleBalanced": "balanced",
    "csetWebrtcBundleMaxBundle": "max-bundle (recommended)",
    "csetWebrtcBundleMaxCompat": "max-compat",
    "csetWebrtcMux": "RTCP mux policy",
    "csetWebrtcMuxReq": "require (recommended)",
    "csetWebrtcMuxNeg": "negotiate",
    "csetWizStep": "Step",
    "csetWizOf": "of",
    "csetWizNext": "Next",
    "csetWizBack": "Back",
    "csetWiz1Title": "General",
    "csetWiz2Title": "Language & alerts",
    "csetWiz3Title": "Calls & media",
    "csetWiz4Title": "Account & plan",
    "csetWiz5Title": "Safety",
    "csetAdvancedCalls": "Advanced call & WebRTC",
    "csetAdvancedCallsSubtitle": "For power users — ICE, codecs, device tuning",
}

cset_he = {
    "csetTitle": "הגדרות",
    "csetProfile": "פרופיל",
    "csetName": "שם",
    "csetPhone": "טלפון",
    "csetEmail": "כתובת מייל",
    "csetLanguage": "שפה",
    "csetHebrew": "עברית",
    "csetEnglish": "English",
    "csetRussian": "Русский",
    "csetNotifications": "התראות",
    "csetNotifyEmergency": "התראות חירום",
    "csetNotifyUpdates": "עדכוני מערכת",
    "csetNotifySms": "SMS",
    "csetSubscription": "מנוי",
    "csetCurrentPlan": "תוכנית נוכחית",
    "csetUpgrade": "שדרג",
    "csetManagePayment": "ניהול תשלום",
    "csetLawyerSettings": "הגדרות עורך דין",
    "csetAvailability": "זמינות",
    "csetSpecializations": "התמחויות",
    "csetContactLinks": "קישורי יצירת קשר",
    "csetWhatsapp": "WhatsApp",
    "csetTelegram": "Telegram",
    "csetAdminSettings": "הגדרות מנהל",
    "csetSystemEmail": "מייל מערכת",
    "csetMaintenanceMode": "מצב תחזוקה",
    "csetMaxFileSizeMb": "גודל קובץ מקסימלי (MB)",
    "csetDefaultQuotaMb": "מכסת קבצים ברירת מחדל (MB)",
    "csetDanger": "אזור מסוכן",
    "csetDeleteAccount": "מחק חשבון",
    "csetDeleteConfirm": "פעולה זו בלתי הפיכה. לאשר?",
    "csetSave": "שמור שינויים",
    "csetSaved": "הגדרות נשמרו",
    "csetCancel": "ביטול",
    "csetYes": "כן",
    "csetNo": "לא",
    "csetLogout": "התנתק",
    "csetLegalSection": "מסמכים משפטיים",
    "csetPrivacyPolicy": "מדיניות פרטיות",
    "csetTermsOfService": "תנאי שימוש",
    "csetDeployBuild": "מזהה גרסה",
    "csetAddLink": "הוסף קישור",
    "csetPlanFree": "חינמי",
    "csetPlanBasic": "בסיסי",
    "csetPlanPro": "מקצועי",
    "csetAgoraCallTitle": "שיחות וידאו/אודיו (Agora)",
    "csetAgoraCallBody": "שיחות הווידאו והאודיו ב-VETO מנותבות דרך Agora. אין צורך בהגדרת STUN/TURN ידנית. ודאו הרשאות מצלמה ומיקרופון במכשיר.",
    "csetWebrtcTitle": "שיחות WebRTC",
    "csetWebrtcHint": "חל על השיחה הבאה. STUN מההגדרות כאן; אם בשרת הוגדרו TURN/ICE (משתני סביבה), הם יתווספו אוטומטית לשיחה.",
    "csetWebrtcIce": "רשימת STUN",
    "csetWebrtcIceMin": "מינימלי (3 שרתים)",
    "csetWebrtcIceExt": "מורחב (5 שרתים)",
    "csetWebrtcPool": "גודל מאגר ICE",
    "csetWebrtcEcho": "ביטול הד (אודיו)",
    "csetWebrtcNoise": "דיכוי רעש",
    "csetWebrtcAgc": "בקרת רווח אוטומטית",
    "csetWebrtcRes": "רזולוציית וידאו",
    "csetWebrtcResSd": "SD ‎640×480",
    "csetWebrtcResHd": "HD ‎1280×720",
    "csetWebrtcResFhd": "Full HD ‎1920×1080",
    "csetWebrtcFacing": "כיוון מצלמה",
    "csetWebrtcFacingUser": "קדמית (selfie)",
    "csetWebrtcFacingEnv": "אחורית",
    "csetWebrtcBundle": "מדיניות Bundle",
    "csetWebrtcBundleBalanced": "balanced",
    "csetWebrtcBundleMaxBundle": "max-bundle (מומלץ)",
    "csetWebrtcBundleMaxCompat": "max-compat",
    "csetWebrtcMux": "RTCP mux",
    "csetWebrtcMuxReq": "require (מומלץ)",
    "csetWebrtcMuxNeg": "negotiate",
    "csetWizStep": "שלב",
    "csetWizOf": "מתוך",
    "csetWizNext": "הבא",
    "csetWizBack": "חזרה",
    "csetWiz1Title": "כללי",
    "csetWiz2Title": "שפה והתראות",
    "csetWiz3Title": "שיחות ומדיה",
    "csetWiz4Title": "חשבון ומנוי",
    "csetWiz5Title": "בטיחות",
    "csetAdvancedCalls": "שיחות ו-WebRTC מתקדם",
    "csetAdvancedCallsSubtitle": "למשתמשים מתקדמים — ICE, קודקים, כיוון מכשיר",
}

cset_ru = {
    "csetTitle": "Настройки",
    "csetProfile": "Профиль",
    "csetName": "Имя",
    "csetPhone": "Телефон",
    "csetEmail": "Email",
    "csetLanguage": "Язык",
    "csetHebrew": "עברית",
    "csetEnglish": "English",
    "csetRussian": "Русский",
    "csetNotifications": "Уведомления",
    "csetNotifyEmergency": "Экстренные уведомления",
    "csetNotifyUpdates": "Системные обновления",
    "csetNotifySms": "SMS-уведомления",
    "csetSubscription": "Подписка",
    "csetCurrentPlan": "Текущий план",
    "csetUpgrade": "Обновить",
    "csetManagePayment": "Управление оплатой",
    "csetLawyerSettings": "Настройки адвоката",
    "csetAvailability": "Доступность",
    "csetSpecializations": "Специализации",
    "csetContactLinks": "Контакты",
    "csetWhatsapp": "WhatsApp",
    "csetTelegram": "Telegram",
    "csetAdminSettings": "Настройки администратора",
    "csetSystemEmail": "Системный email",
    "csetMaintenanceMode": "Режим обслуживания",
    "csetMaxFileSizeMb": "Макс. размер файла (МБ)",
    "csetDefaultQuotaMb": "Квота файлов по умолчанию (МБ)",
    "csetDanger": "Опасная зона",
    "csetDeleteAccount": "Удалить аккаунт",
    "csetDeleteConfirm": "Это необратимо. Подтвердить?",
    "csetSave": "Сохранить изменения",
    "csetSaved": "Настройки сохранены",
    "csetCancel": "Отмена",
    "csetYes": "Да",
    "csetNo": "Нет",
    "csetLogout": "Выйти",
    "csetLegalSection": "Документы",
    "csetPrivacyPolicy": "Конфиденциальность",
    "csetTermsOfService": "Условия",
    "csetDeployBuild": "Сборка",
    "csetAddLink": "Добавить ссылку",
    "csetPlanFree": "Бесплатный",
    "csetPlanBasic": "Базовый",
    "csetPlanPro": "Pro",
    "csetAgoraCallTitle": "Видео/аудио (Agora)",
    "csetAgoraCallBody": "Звонки VETO идут через Agora RTC. Ручная настройка STUN/TURN не нужна. Разрешите камеру и микрофон в настройках устройства или браузера.",
    "csetWebrtcTitle": "Звонки WebRTC",
    "csetWebrtcHint": "Со следующего звонка. STUN — здесь; TURN/ICE с сервера (env) подмешиваются автоматически.",
    "csetWebrtcIce": "Набор STUN",
    "csetWebrtcIceMin": "Минимальный (3 сервера)",
    "csetWebrtcIceExt": "Расширенный (5 серверов)",
    "csetWebrtcPool": "Размер пула ICE",
    "csetWebrtcEcho": "Подавление эха",
    "csetWebrtcNoise": "Шумоподавление",
    "csetWebrtcAgc": "Автоусиление (AGC)",
    "csetWebrtcRes": "Разрешение видео",
    "csetWebrtcResSd": "SD 640×480",
    "csetWebrtcResHd": "HD 1280×720",
    "csetWebrtcResFhd": "Full HD 1920×1080",
    "csetWebrtcFacing": "Камера",
    "csetWebrtcFacingUser": "Передняя",
    "csetWebrtcFacingEnv": "Задняя",
    "csetWebrtcBundle": "Политика bundle",
    "csetWebrtcBundleBalanced": "balanced",
    "csetWebrtcBundleMaxBundle": "max-bundle (рекомендуется)",
    "csetWebrtcBundleMaxCompat": "max-compat",
    "csetWebrtcMux": "Политика RTCP mux",
    "csetWebrtcMuxReq": "require (рекомендуется)",
    "csetWebrtcMuxNeg": "negotiate",
    "csetWizStep": "Шаг",
    "csetWizOf": "из",
    "csetWizNext": "Далее",
    "csetWizBack": "Назад",
    "csetWiz1Title": "Общие",
    "csetWiz2Title": "Язык и уведомления",
    "csetWiz3Title": "Звонки и медиа",
    "csetWiz4Title": "Аккаунт и план",
    "csetWiz5Title": "Безопасность",
    "csetAdvancedCalls": "Расширенные звонки и WebRTC",
    "csetAdvancedCallsSubtitle": "Для опытных — ICE, кодеки, настройка устройства",
}

# Lawyer settings — prefix lset_
lset_en = {
    "lsetTitle": "Lawyer Settings",
    "lsetAvailability": "Availability",
    "lsetAvailableNow": "Available for cases",
    "lsetAvailableDesc": "When active, clients can see and send requests to you",
    "lsetSchedule": "Working Hours",
    "lsetScheduleDesc": "Set your working hours for each day",
    "lsetMon": "Mon",
    "lsetTue": "Tue",
    "lsetWed": "Wed",
    "lsetThu": "Thu",
    "lsetFri": "Fri",
    "lsetSat": "Sat",
    "lsetSun": "Sun",
    "lsetFrom": "From",
    "lsetTo": "To",
    "lsetClosed": "Closed",
    "lsetSpecializations": "Specializations",
    "lsetSpecDesc": "Add your areas of expertise",
    "lsetAddSpec": "Add specialization",
    "lsetAddSpecHint": "e.g. Labor law",
    "lsetContact": "Contact Links",
    "lsetWhatsapp": "WhatsApp number",
    "lsetWhatsappHint": "+972501234567",
    "lsetTelegram": "Telegram username",
    "lsetTelegramHint": "@username",
    "lsetResponseTime": "Avg. response time",
    "lsetMinutes": "minutes",
    "lsetNotifications": "Notifications",
    "lsetNotifyEmergency": "Emergency alerts",
    "lsetNotifyNewCase": "New case alert",
    "lsetNotifyUpdates": "System updates",
    "lsetNotifySms": "SMS alerts",
    "lsetLicense": "License Details",
    "lsetLicenseNumber": "License number",
    "lsetBarAssociation": "Bar association",
    "lsetLanguages": "Languages handled",
    "lsetAccount": "Account",
    "lsetAdd": "Add",
}

lset_he = {
    "lsetTitle": "הגדרות עורך דין",
    "lsetAvailability": "זמינות",
    "lsetAvailableNow": "זמין לקבלת תיקים",
    "lsetAvailableDesc": "כשהוא פעיל, הלקוחות יוכלו לראות אותך ולשלוח בקשות",
    "lsetSchedule": "שעות פעילות",
    "lsetScheduleDesc": "הגדר את שעות העבודה שלך לכל יום",
    "lsetMon": "שני",
    "lsetTue": "שלישי",
    "lsetWed": "רביעי",
    "lsetThu": "חמישי",
    "lsetFri": "שישי",
    "lsetSat": "שבת",
    "lsetSun": "ראשון",
    "lsetFrom": "מ",
    "lsetTo": "עד",
    "lsetClosed": "סגור",
    "lsetSpecializations": "תחומי התמחות",
    "lsetSpecDesc": "הוסף את תחומי ההתמחות שלך",
    "lsetAddSpec": "הוסף התמחות",
    "lsetAddSpecHint": "לדוגמה: דיני עבודה",
    "lsetContact": "קישורי יצירת קשר",
    "lsetWhatsapp": "מספר WhatsApp",
    "lsetWhatsappHint": "+972501234567",
    "lsetTelegram": "שם משתמש Telegram",
    "lsetTelegramHint": "@username",
    "lsetResponseTime": "זמן מענה ממוצע",
    "lsetMinutes": "דקות",
    "lsetNotifications": "התראות",
    "lsetNotifyEmergency": "התראות חירום",
    "lsetNotifyNewCase": "תיק חדש",
    "lsetNotifyUpdates": "עדכוני מערכת",
    "lsetNotifySms": "SMS",
    "lsetLicense": "פרטי רישיון",
    "lsetLicenseNumber": "מספר רישיון",
    "lsetBarAssociation": "לשכת עורכי הדין",
    "lsetLanguages": "שפות טיפול",
    "lsetAccount": "חשבון",
    "lsetAdd": "הוסף",
}

lset_ru = {
    "lsetTitle": "Настройки адвоката",
    "lsetAvailability": "Доступность",
    "lsetAvailableNow": "Доступен для дел",
    "lsetAvailableDesc": "Когда включено, клиенты могут видеть вас и отправлять запросы",
    "lsetSchedule": "Рабочие часы",
    "lsetScheduleDesc": "Установите рабочие часы для каждого дня",
    "lsetMon": "Пн",
    "lsetTue": "Вт",
    "lsetWed": "Ср",
    "lsetThu": "Чт",
    "lsetFri": "Пт",
    "lsetSat": "Сб",
    "lsetSun": "Вс",
    "lsetFrom": "С",
    "lsetTo": "До",
    "lsetClosed": "Закрыто",
    "lsetSpecializations": "Специализации",
    "lsetSpecDesc": "Добавьте ваши области экспертизы",
    "lsetAddSpec": "Добавить специализацию",
    "lsetAddSpecHint": "Например: трудовое право",
    "lsetContact": "Контакты",
    "lsetWhatsapp": "Номер WhatsApp",
    "lsetWhatsappHint": "+972501234567",
    "lsetTelegram": "Имя пользователя Telegram",
    "lsetTelegramHint": "@username",
    "lsetResponseTime": "Среднее время ответа",
    "lsetMinutes": "минут",
    "lsetNotifications": "Уведомления",
    "lsetNotifyEmergency": "Экстренные уведомления",
    "lsetNotifyNewCase": "Новое дело",
    "lsetNotifyUpdates": "Системные обновления",
    "lsetNotifySms": "SMS-уведомления",
    "lsetLicense": "Данные лицензии",
    "lsetLicenseNumber": "Номер лицензии",
    "lsetBarAssociation": "Коллегия адвокатов",
    "lsetLanguages": "Языки обслуживания",
    "lsetAccount": "Аккаунт",
    "lsetAdd": "Добавить",
}

def merge(locale: str) -> dict:
    out = {}
    out.update(landing[locale])
    out.update(pango_extra[locale])
    if locale == "en":
        out.update(cset_en)
        out.update(lset_en)
    elif locale == "he":
        out.update(cset_he)
        out.update(lset_he)
    else:
        out.update(cset_ru)
        out.update(lset_ru)
    # shared lawyer/citizen duplicates: save, cancel, etc. — use cset for settings screen, lawyer screen uses lset + AppLocalizations for save from cset
    out["lsetSave"] = {"en": "Save changes", "he": "שמור שינויים", "ru": "Сохранить"}[locale]
    out["lsetSaved"] = {"en": "Settings saved", "he": "ההגדרות נשמרו", "ru": "Настройки сохранены"}[locale]
    out["lsetCancel"] = {"en": "Cancel", "he": "ביטול", "ru": "Отмена"}[locale]
    out["lsetYes"] = {"en": "Yes", "he": "כן", "ru": "Да"}[locale]
    out["lsetNo"] = {"en": "No", "he": "לא", "ru": "Нет"}[locale]
    out["lsetLogout"] = {"en": "Sign out", "he": "התנתק", "ru": "Выйти"}[locale]
    out["lsetDeleteAccount"] = {"en": "Delete account", "he": "מחק חשבון", "ru": "Удалить аккаунт"}[locale]
    out["lsetDeleteConfirm"] = {
        "en": "This is irreversible. Confirm?",
        "he": "מחיקת חשבון היא בלתי הפיכה. לאשר?",
        "ru": "Это необратимо. Подтвердить?",
    }[locale]
    return out


def write_arb(filename: str, locale: str, data: dict):
    payload = {"@@locale": locale, **data}
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / filename
    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
        f.write("\n")


def main():
    write_arb("app_en.arb", "en", merge("en"))
    write_arb("app_he.arb", "he", merge("he"))
    write_arb("app_ru.arb", "ru", merge("ru"))
    print("Wrote", OUT / "app_en.arb")


if __name__ == "__main__":
    main()
