import fs from "fs";
const text = fs.readFileSync("lib/screens/login_screen.dart", "utf8");
function parseBlock(locale) {
  const startMark = `'${locale}': {`;
  const start = text.indexOf(startMark);
  let i = start + startMark.length;
  let depth = 1;
  while (i < text.length && depth > 0) {
    if (text[i] === "{") depth++;
    else if (text[i] === "}") depth--;
    i++;
  }
  const block = text.slice(start + startMark.length, i - 1);
  const out = {};
  const re = /'([^']+)':\s*((?:'(?:\\'|[^'])*'|"(?:\\"|[^"])*"))/gs;
  let m;
  while ((m = re.exec(block))) {
    const k = m[1];
    let raw = m[2];
    let v;
    if (raw.startsWith("'")) v = raw.slice(1, -1).replace(/\\'/g, "'");
    else v = raw.slice(1, -1).replace(/\\"/g, '"');
    out[k] = v;
  }
  return out;
}
function toGetter(k) {
  return (
    "login" +
    k.split("_").map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join("")
  );
}
const he = parseBlock("he");
const keys = Object.keys(he).sort();
const cases = keys
  .map(
    (k) => `    case '${k}': return l.${toGetter(k)};`,
  )
  .join("\n");
const dart = `// GENERATED by tool/gen_login_switch.mjs — do not edit by hand
import '../l10n/app_localizations.dart';

String loginT(AppLocalizations l, String key) {
  switch (key) {
${cases}
    default:
      return key;
  }
}
`;
fs.writeFileSync("lib/screens/login_l10n_lookup.dart", dart);
console.log("wrote login_l10n_lookup.dart", keys.length);
