/**
 * Generates lib/screens/admin/admin_l10n_lookups.dart from app_en.arb adm* keys.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const arbPath = path.join(root, "lib/l10n/app_en.arb");

function arbToCaseKey(arbKey, prefix) {
  const rest = arbKey.slice(prefix.length);
  const camel = rest.charAt(0).toLowerCase() + rest.slice(1);
  if (prefix === "admShell") {
    return camel.replace(/([A-Z])/g, "_$1").toLowerCase().replace(/^_/, "");
  }
  return camel;
}

function collectArbKeys() {
  const raw = fs.readFileSync(arbPath, "utf8");
  const keys = [];
  for (const m of raw.matchAll(/^  "([^"]+)":/gm)) keys.push(m[1]);
  return keys;
}

function genSwitch(fnName, prefix, arbKeys) {
  const subset = arbKeys.filter((k) => {
    if (!k.startsWith(prefix)) return false;
    if (prefix === "adm") return !k.startsWith("admShell");
    return true;
  });
  subset.sort();
  const cases = subset.map(
    (ak) => `    case '${arbToCaseKey(ak, prefix)}': return l.${ak};`
  );
  return `String ${fnName}(AppLocalizations l, String key) {
  switch (key) {
${cases.join("\n")}
    default:
      return key;
  }
}`;
}

function main() {
  const arbKeys = collectArbKeys();
  const adm = genSwitch("admT", "adm", arbKeys);
  const shell = genSwitch("admShellT", "admShell", arbKeys);
  const dash = genSwitch("adashT", "adash", arbKeys);
  const sub = genSwitch("subAdmT", "subAdm", arbKeys);

  const dart = `// GENERATED by tool/gen_admin_lookups.mjs
import '../../l10n/app_localizations.dart';

${adm}

${shell}

${dash}

${sub}
`;
  fs.writeFileSync(path.join(root, "lib/screens/admin/admin_l10n_lookups.dart"), dart);
  console.log("wrote admin_l10n_lookups.dart");
}

main();
