import fs from "fs";

function arbToCopyKey(arbKey, prefix) {
  const s = arbKey.slice(prefix.length);
  return s.charAt(0).toLowerCase() + s.slice(1);
}

function genFunction(name, prefix, enPath) {
  const lines = fs.readFileSync(enPath, "utf8").split("\n");
  const cases = [];
  for (const line of lines) {
    const m = line.match(/^  "([^"]+)":/);
    if (!m) continue;
    const ak = m[1];
    if (!ak.startsWith(prefix)) continue;
    const ck = arbToCopyKey(ak, prefix);
    cases.push(`    case '${ck}': return l.${ak};`);
  }
  return `String ${name}(AppLocalizations l, String key) {
  switch (key) {
${cases.join("\n")}
    default:
      return key;
  }
}`;
}

const lawyer = genFunction(
  "lawyerDashT",
  "lawyerDash",
  "tool/_extract_lawyerDash_en.txt",
);
const prof = genFunction(
  "profScreenT",
  "profScreen",
  "tool/_extract_profScreen_en.txt",
);

const dart = `// GENERATED by tool/gen_dash_prof_lookup.mjs
import '../l10n/app_localizations.dart';

${lawyer}

${prof}
`;
fs.writeFileSync("lib/screens/dash_profile_l10n_lookup.dart", dart);
console.log("wrote dash_profile_l10n_lookup.dart");
