// GENERATED by tool/gen_dash_prof_lookup.mjs
import '../l10n/app_localizations.dart';

String lawyerDashT(AppLocalizations l, String key) {
  switch (key) {
    case 'accept': return l.lawyerDashAccept;
    case 'accepted': return l.lawyerDashAccepted;
    case 'activity': return l.lawyerDashActivity;
    case 'activitySubtitle': return l.lawyerDashActivitySubtitle;
    case 'activityTitle': return l.lawyerDashActivityTitle;
    case 'emptyBody': return l.lawyerDashEmptyBody;
    case 'emptyHint': return l.lawyerDashEmptyHint;
    case 'emptyTitle': return l.lawyerDashEmptyTitle;
    case 'eyebrow': return l.lawyerDashEyebrow;
    case 'liveDialog': return l.lawyerDashLiveDialog;
    case 'logout': return l.lawyerDashLogout;
    case 'profile': return l.lawyerDashProfile;
    case 'queue': return l.lawyerDashQueue;
    case 'reject': return l.lawyerDashReject;
    case 'rejected': return l.lawyerDashRejected;
    case 'request': return l.lawyerDashRequest;
    case 'requestDetails': return l.lawyerDashRequestDetails;
    case 'requestFrom': return l.lawyerDashRequestFrom;
    case 'requestUnknown': return l.lawyerDashRequestUnknown;
    case 'response': return l.lawyerDashResponse;
    case 'responseValue': return l.lawyerDashResponseValue;
    case 'shift': return l.lawyerDashShift;
    case 'shiftBody': return l.lawyerDashShiftBody;
    case 'shiftTitle': return l.lawyerDashShiftTitle;
    case 'status': return l.lawyerDashStatus;
    case 'statusHelp': return l.lawyerDashStatusHelp;
    case 'statusOffline': return l.lawyerDashStatusOffline;
    case 'statusOnline': return l.lawyerDashStatusOnline;
    case 'subtitle': return l.lawyerDashSubtitle;
    case 'title': return l.lawyerDashTitle;
    case 'noPendingAlerts': return l.lawyerDashNoPendingAlerts;
    case 'vaultRequiresCase': return l.lawyerDashVaultRequiresCase;
    case 'userFallback': return l.lawyerDashUserFallback;
    default:
      return key;
  }
}

String profScreenT(AppLocalizations l, String key) {
  switch (key) {
    case 'badgePremium': return l.profScreenBadgePremium;
    case 'badgeSince': return l.profScreenBadgeSince;
    case 'badgeVerified': return l.profScreenBadgeVerified;
    case 'language': return l.profScreenLanguage;
    case 'logout': return l.profScreenLogout;
    case 'name': return l.profScreenName;
    case 'nameEmpty': return l.profScreenNameEmpty;
    case 'nameHint': return l.profScreenNameHint;
    case 'phone': return l.profScreenPhone;
    case 'role': return l.profScreenRole;
    case 'save': return l.profScreenSave;
    case 'saveError': return l.profScreenSaveError;
    case 'saved': return l.profScreenSaved;
    case 'statCases': return l.profScreenStatCases;
    case 'statDays': return l.profScreenStatDays;
    case 'statFiles': return l.profScreenStatFiles;
    case 'subscriptionBody': return l.profScreenSubscriptionBody;
    case 'subscriptionCta': return l.profScreenSubscriptionCta;
    case 'subscriptionTitle': return l.profScreenSubscriptionTitle;
    case 'title': return l.profScreenTitle;
    default:
      return key;
  }
}
