// GENERATED by tool/gen_admin_lookups.mjs
import '../../l10n/app_localizations.dart';

String admT(AppLocalizations l, String key) {
  switch (key) {
    case 'active': return l.admActive;
    case 'add': return l.admAdd;
    case 'addLawyer': return l.admAddLawyer;
    case 'addUser': return l.admAddUser;
    case 'admin': return l.admAdmin;
    case 'adminPanel': return l.admAdminPanel;
    case 'allLawyers': return l.admAllLawyers;
    case 'allUsers': return l.admAllUsers;
    case 'appVersion': return l.admAppVersion;
    case 'approve': return l.admApprove;
    case 'approveError': return l.admApproveError;
    case 'approveSuccess': return l.admApproveSuccess;
    case 'available': return l.admAvailable;
    case 'availableForCalls': return l.admAvailableForCalls;
    case 'badgeActive': return l.admBadgeActive;
    case 'cacheReset': return l.admCacheReset;
    case 'cacheResetSnack': return l.admCacheResetSnack;
    case 'cancel': return l.admCancel;
    case 'changeStatus': return l.admChangeStatus;
    case 'citizen': return l.admCitizen;
    case 'citizenApp': return l.admCitizenApp;
    case 'commAgora': return l.admCommAgora;
    case 'commFcm': return l.admCommFcm;
    case 'commGemini': return l.admCommGemini;
    case 'commTitle': return l.admCommTitle;
    case 'commTwilio': return l.admCommTwilio;
    case 'connected': return l.admConnected;
    case 'database': return l.admDatabase;
    case 'delete': return l.admDelete;
    case 'deleteEvent': return l.admDeleteEvent;
    case 'deleteEventConfirm': return l.admDeleteEventConfirm;
    case 'deleteLawyer': return l.admDeleteLawyer;
    case 'deleteLawyerConfirm': return l.admDeleteLawyerConfirm;
    case 'deleteUser': return l.admDeleteUser;
    case 'deleteUserConfirm': return l.admDeleteUserConfirm;
    case 'dispatchMaxLawyers': return l.admDispatchMaxLawyers;
    case 'dispatchRadiusKm': return l.admDispatchRadiusKm;
    case 'dispatchTimeoutSec': return l.admDispatchTimeoutSec;
    case 'dispatchingTitle': return l.admDispatchingTitle;
    case 'edit': return l.admEdit;
    case 'editLawyer': return l.admEditLawyer;
    case 'editUser': return l.admEditUser;
    case 'email': return l.admEmail;
    case 'emergencyLogs': return l.admEmergencyLogs;
    case 'exempt': return l.admExempt;
    case 'experience': return l.admExperience;
    case 'experienceYears': return l.admExperienceYears;
    case 'fixedOtp': return l.admFixedOtp;
    case 'fixedOtpHint': return l.admFixedOtpHint;
    case 'fullName': return l.admFullName;
    case 'language': return l.admLanguage;
    case 'lawyerPrefix': return l.admLawyerPrefix;
    case 'lawyers': return l.admLawyers;
    case 'license': return l.admLicense;
    case 'loading': return l.admLoading;
    case 'logout': return l.admLogout;
    case 'maintenanceHint': return l.admMaintenanceHint;
    case 'maintenanceMode': return l.admMaintenanceMode;
    case 'maintenanceTitle': return l.admMaintenanceTitle;
    case 'manualExempt': return l.admManualExempt;
    case 'manualExemptHint': return l.admManualExemptHint;
    case 'noEmergencyEvents': return l.admNoEmergencyEvents;
    case 'noLawyers': return l.admNoLawyers;
    case 'noName': return l.admNoName;
    case 'noPendingLawyers': return l.admNoPendingLawyers;
    case 'noUsers': return l.admNoUsers;
    case 'online': return l.admOnline;
    case 'openApp': return l.admOpenApp;
    case 'pending': return l.admPending;
    case 'pendingApprovals': return l.admPendingApprovals;
    case 'pendingApprovalsAction': return l.admPendingApprovalsAction;
    case 'pendingLawyersTitle': return l.admPendingLawyersTitle;
    case 'pendingSingle': return l.admPendingSingle;
    case 'pendingStatus': return l.admPendingStatus;
    case 'phone': return l.admPhone;
    case 'quickStats': return l.admQuickStats;
    case 'refresh': return l.admRefresh;
    case 'reject': return l.admReject;
    case 'rejectError': return l.admRejectError;
    case 'rejectRequest': return l.admRejectRequest;
    case 'rejectRequestConfirm': return l.admRejectRequestConfirm;
    case 'rejectSuccess': return l.admRejectSuccess;
    case 'resolved': return l.admResolved;
    case 'role': return l.admRole;
    case 'save': return l.admSave;
    case 'saveLawyerFailed': return l.admSaveLawyerFailed;
    case 'saveUserFailed': return l.admSaveUserFailed;
    case 'serverStatus': return l.admServerStatus;
    case 'settingUpdateError': return l.admSettingUpdateError;
    case 'settingUpdated': return l.admSettingUpdated;
    case 'specializations': return l.admSpecializations;
    case 'specializationsLabel': return l.admSpecializationsLabel;
    case 'statusAccepted': return l.admStatusAccepted;
    case 'statusCancelled': return l.admStatusCancelled;
    case 'statusCompleted': return l.admStatusCompleted;
    case 'statusDispatching': return l.admStatusDispatching;
    case 'statusDocumentation': return l.admStatusDocumentation;
    case 'statusFailed': return l.admStatusFailed;
    case 'statusInProgress': return l.admStatusInProgress;
    case 'systemOverview': return l.admSystemOverview;
    case 'systemSettings': return l.admSystemSettings;
    case 'unavailable': return l.admUnavailable;
    case 'unknown': return l.admUnknown;
    case 'unverified': return l.admUnverified;
    case 'userManagement': return l.admUserManagement;
    case 'users': return l.admUsers;
    case 'verified': return l.admVerified;
    default:
      return key;
  }
}

String admShellT(AppLocalizations l, String key) {
  switch (key) {
    case 'admin': return l.admShellAdmin;
    case 'admin_group': return l.admShellAdminGroup;
    case 'dashboard': return l.admShellDashboard;
    case 'env_production': return l.admShellEnvProduction;
    case 'env_staging': return l.admShellEnvStaging;
    case 'lawyers': return l.admShellLawyers;
    case 'logs': return l.admShellLogs;
    case 'notifications': return l.admShellNotifications;
    case 'panel': return l.admShellPanel;
    case 'pending': return l.admShellPending;
    case 'refresh': return l.admShellRefresh;
    case 'search_hint': return l.admShellSearchHint;
    case 'settings': return l.admShellSettings;
    case 'subscriptions': return l.admShellSubscriptions;
    case 'system_group': return l.admShellSystemGroup;
    case 'users': return l.admShellUsers;
    default:
      return key;
  }
}

String adashT(AppLocalizations l, String key) {
  switch (key) {
    case 'active': return l.adashActive;
    case 'allLawyers': return l.adashAllLawyers;
    case 'allUsers': return l.adashAllUsers;
    case 'backend': return l.adashBackend;
    case 'db': return l.adashDb;
    case 'dispatchedStatus': return l.adashDispatchedStatus;
    case 'emergencyLogs': return l.adashEmergencyLogs;
    case 'events': return l.adashEvents;
    case 'eventsMonth': return l.adashEventsMonth;
    case 'eventsToday': return l.adashEventsToday;
    case 'eventsWeek': return l.adashEventsWeek;
    case 'lawyers': return l.adashLawyers;
    case 'loading': return l.adashLoading;
    case 'noActivity': return l.adashNoActivity;
    case 'offline': return l.adashOffline;
    case 'online': return l.adashOnline;
    case 'openStatus': return l.adashOpenStatus;
    case 'pending': return l.adashPending;
    case 'pendingLawyers': return l.adashPendingLawyers;
    case 'quickLinks': return l.adashQuickLinks;
    case 'recentActivity': return l.adashRecentActivity;
    case 'refresh': return l.adashRefresh;
    case 'resolvedStatus': return l.adashResolvedStatus;
    case 'socket': return l.adashSocket;
    case 'subscriptions': return l.adashSubscriptions;
    case 'systemHealth': return l.adashSystemHealth;
    case 'title': return l.adashTitle;
    case 'unknown': return l.adashUnknown;
    case 'users': return l.adashUsers;
    default:
      return key;
  }
}

String subAdmT(AppLocalizations l, String key) {
  switch (key) {
    case 'accountEnabled': return l.subAdmAccountEnabled;
    case 'actions': return l.subAdmActions;
    case 'activate': return l.subAdmActivate;
    case 'active': return l.subAdmActive;
    case 'allTime': return l.subAdmAllTime;
    case 'amount': return l.subAdmAmount;
    case 'arpu': return l.subAdmArpu;
    case 'cancel': return l.subAdmCancel;
    case 'cancelled': return l.subAdmCancelled;
    case 'clearExpiry': return l.subAdmClearExpiry;
    case 'confirmActivate': return l.subAdmConfirmActivate;
    case 'confirmCancel': return l.subAdmConfirmCancel;
    case 'confirmDeleteUser': return l.subAdmConfirmDeleteUser;
    case 'confirmExtend': return l.subAdmConfirmExtend;
    case 'delete': return l.subAdmDelete;
    case 'deleted': return l.subAdmDeleted;
    case 'edit': return l.subAdmEdit;
    case 'emailLabel': return l.subAdmEmailLabel;
    case 'endDate': return l.subAdmEndDate;
    case 'errorSave': return l.subAdmErrorSave;
    case 'expired': return l.subAdmExpired;
    case 'extend': return l.subAdmExtend;
    case 'freeTier': return l.subAdmFreeTier;
    case 'fullName': return l.subAdmFullName;
    case 'loading': return l.subAdmLoading;
    case 'logFail': return l.subAdmLogFail;
    case 'logGoogle': return l.subAdmLogGoogle;
    case 'logGoogleFail': return l.subAdmLogGoogleFail;
    case 'logOtpFail': return l.subAdmLogOtpFail;
    case 'logOtpOk': return l.subAdmLogOtpOk;
    case 'logOtpReq': return l.subAdmLogOtpReq;
    case 'logRegister': return l.subAdmLogRegister;
    case 'logSuccess': return l.subAdmLogSuccess;
    case 'manualExempt': return l.subAdmManualExempt;
    case 'monthly': return l.subAdmMonthly;
    case 'mrrBadge': return l.subAdmMrrBadge;
    case 'newPlan': return l.subAdmNewPlan;
    case 'newPlanHint': return l.subAdmNewPlanHint;
    case 'no': return l.subAdmNo;
    case 'noLogs': return l.subAdmNoLogs;
    case 'noSubs': return l.subAdmNoSubs;
    case 'phoneLabel': return l.subAdmPhoneLabel;
    case 'plan': return l.subAdmPlan;
    case 'planBasic': return l.subAdmPlanBasic;
    case 'planFree': return l.subAdmPlanFree;
    case 'planNone': return l.subAdmPlanNone;
    case 'planPro': return l.subAdmPlanPro;
    case 'plansTitle': return l.subAdmPlansTitle;
    case 'premiumMonthly': return l.subAdmPremiumMonthly;
    case 'premiumYearly': return l.subAdmPremiumYearly;
    case 'refresh': return l.subAdmRefresh;
    case 'renewalsThisMonth': return l.subAdmRenewalsThisMonth;
    case 'retry': return l.subAdmRetry;
    case 'revenue': return l.subAdmRevenue;
    case 'save': return l.subAdmSave;
    case 'search': return l.subAdmSearch;
    case 'startDate': return l.subAdmStartDate;
    case 'status': return l.subAdmStatus;
    case 'statusActive': return l.subAdmStatusActive;
    case 'statusCancelled': return l.subAdmStatusCancelled;
    case 'statusExpired': return l.subAdmStatusExpired;
    case 'statusFree': return l.subAdmStatusFree;
    case 'statusNoSub': return l.subAdmStatusNoSub;
    case 'statusTrial': return l.subAdmStatusTrial;
    case 'statusUnverified': return l.subAdmStatusUnverified;
    case 'subscribed': return l.subAdmSubscribed;
    case 'subscriptionExpiry': return l.subAdmSubscriptionExpiry;
    case 'tabLogs': return l.subAdmTabLogs;
    case 'tabUsers': return l.subAdmTabUsers;
    case 'title': return l.subAdmTitle;
    case 'total': return l.subAdmTotal;
    case 'updated': return l.subAdmUpdated;
    case 'user': return l.subAdmUser;
    case 'yes': return l.subAdmYes;
    default:
      return key;
  }
}
